//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Controller_Tests : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Left_Trigger_Click
        {
            get
            {
                return SteamVR_Actions.controller_Tests_Left_Trigger_Click;
            }
        }
        
        public virtual SteamVR_Action_Single Left_Trigger_Pull
        {
            get
            {
                return SteamVR_Actions.controller_Tests_Left_Trigger_Pull;
            }
        }
        
        public virtual SteamVR_Action_Single Left_Trigger_Touch
        {
            get
            {
                return SteamVR_Actions.controller_Tests_Left_Trigger_Touch;
            }
        }
        
        public virtual SteamVR_Action_Boolean Right_Trigger_Click
        {
            get
            {
                return SteamVR_Actions.controller_Tests_Right_Trigger_Click;
            }
        }
        
        public virtual SteamVR_Action_Single Right_Trigger_Pull
        {
            get
            {
                return SteamVR_Actions.controller_Tests_Right_Trigger_Pull;
            }
        }
        
        public virtual SteamVR_Action_Single Right_Trigger_Touch
        {
            get
            {
                return SteamVR_Actions.controller_Tests_Right_Trigger_Touch;
            }
        }
        
        public virtual SteamVR_Action_Boolean Left_System_Click
        {
            get
            {
                return SteamVR_Actions.controller_Tests_Left_System_Click;
            }
        }
        
        public virtual SteamVR_Action_Boolean Right_System_Click
        {
            get
            {
                return SteamVR_Actions.controller_Tests_Right_System_Click;
            }
        }
        
        public virtual SteamVR_Action_Boolean Left_A_Button
        {
            get
            {
                return SteamVR_Actions.controller_Tests_Left_A_Button;
            }
        }
        
        public virtual SteamVR_Action_Boolean Left_B_Button
        {
            get
            {
                return SteamVR_Actions.controller_Tests_Left_B_Button;
            }
        }
        
        public virtual SteamVR_Action_Boolean Right_A_Button
        {
            get
            {
                return SteamVR_Actions.controller_Tests_Right_A_Button;
            }
        }
        
        public virtual SteamVR_Action_Boolean Right_B_Button
        {
            get
            {
                return SteamVR_Actions.controller_Tests_Right_B_Button;
            }
        }
        
        public virtual SteamVR_Action_Single Left_Grip_Grab
        {
            get
            {
                return SteamVR_Actions.controller_Tests_Left_Grip_Grab;
            }
        }
        
        public virtual SteamVR_Action_Single Left_Grip_Force
        {
            get
            {
                return SteamVR_Actions.controller_Tests_Left_Grip_Force;
            }
        }
        
        public virtual SteamVR_Action_Single Right_Grip_Grab
        {
            get
            {
                return SteamVR_Actions.controller_Tests_Right_Grip_Grab;
            }
        }
        
        public virtual SteamVR_Action_Single Right_Grip_Force
        {
            get
            {
                return SteamVR_Actions.controller_Tests_Right_Grip_Force;
            }
        }
        
        public virtual SteamVR_Action_Single Left_Grab_Pinch
        {
            get
            {
                return SteamVR_Actions.controller_Tests_Left_Grab_Pinch;
            }
        }
        
        public virtual SteamVR_Action_Single Right_Grab_Pinch
        {
            get
            {
                return SteamVR_Actions.controller_Tests_Right_Grab_Pinch;
            }
        }
        
        public virtual SteamVR_Action_Boolean Left_Thumbstick_Click
        {
            get
            {
                return SteamVR_Actions.controller_Tests_Left_Thumbstick_Click;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Left_Thumbstick_Position
        {
            get
            {
                return SteamVR_Actions.controller_Tests_Left_Thumbstick_Position;
            }
        }
        
        public virtual SteamVR_Action_Boolean Left_Thumbstick_Touch
        {
            get
            {
                return SteamVR_Actions.controller_Tests_Left_Thumbstick_Touch;
            }
        }
        
        public virtual SteamVR_Action_Boolean Right_Thumbstick_Click
        {
            get
            {
                return SteamVR_Actions.controller_Tests_Right_Thumbstick_Click;
            }
        }
        
        public virtual SteamVR_Action_Single Right_Thumbstick_Touch
        {
            get
            {
                return SteamVR_Actions.controller_Tests_Right_Thumbstick_Touch;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Right_Thumbstick_Position
        {
            get
            {
                return SteamVR_Actions.controller_Tests_Right_Thumbstick_Position;
            }
        }
        
        public virtual SteamVR_Action_Single Left_Trackpad_Touch
        {
            get
            {
                return SteamVR_Actions.controller_Tests_Left_Trackpad_Touch;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Left_TrackPad_Position
        {
            get
            {
                return SteamVR_Actions.controller_Tests_Left_TrackPad_Position;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Right_TrackPad_Position
        {
            get
            {
                return SteamVR_Actions.controller_Tests_Right_TrackPad_Position;
            }
        }
        
        public virtual SteamVR_Action_Single Right_TrackPad_Touch
        {
            get
            {
                return SteamVR_Actions.controller_Tests_Right_TrackPad_Touch;
            }
        }
        
        public virtual SteamVR_Action_Skeleton Left_Hand_Skeleton
        {
            get
            {
                return SteamVR_Actions.controller_Tests_Left_Hand_Skeleton;
            }
        }
        
        public virtual SteamVR_Action_Skeleton Right_Hand_Skeleton
        {
            get
            {
                return SteamVR_Actions.controller_Tests_Right_Hand_Skeleton;
            }
        }
        
        public virtual SteamVR_Action_Pose Left_Hand_Pose_Base
        {
            get
            {
                return SteamVR_Actions.controller_Tests_Left_Hand_Pose_Base;
            }
        }
        
        public virtual SteamVR_Action_Pose Right_Hand_Pose_base
        {
            get
            {
                return SteamVR_Actions.controller_Tests_Right_Hand_Pose_base;
            }
        }
        
        public virtual SteamVR_Action_Pose Left_Hand_GDC
        {
            get
            {
                return SteamVR_Actions.controller_Tests_Left_Hand_GDC;
            }
        }
        
        public virtual SteamVR_Action_Pose Right_hand_GDC
        {
            get
            {
                return SteamVR_Actions.controller_Tests_Right_hand_GDC;
            }
        }
        
        public virtual SteamVR_Action_Pose Left_Hand_Hand_Grip
        {
            get
            {
                return SteamVR_Actions.controller_Tests_Left_Hand_Hand_Grip;
            }
        }
        
        public virtual SteamVR_Action_Pose Right_Hand_Hand_Grip
        {
            get
            {
                return SteamVR_Actions.controller_Tests_Right_Hand_Hand_Grip;
            }
        }
        
        public virtual SteamVR_Action_Pose Left_Hand_Raw
        {
            get
            {
                return SteamVR_Actions.controller_Tests_Left_Hand_Raw;
            }
        }
        
        public virtual SteamVR_Action_Pose Right_Hand_Raw
        {
            get
            {
                return SteamVR_Actions.controller_Tests_Right_Hand_Raw;
            }
        }
        
        public virtual SteamVR_Action_Pose Left_Hand_Tip
        {
            get
            {
                return SteamVR_Actions.controller_Tests_Left_Hand_Tip;
            }
        }
        
        public virtual SteamVR_Action_Pose Right_hand_Tip
        {
            get
            {
                return SteamVR_Actions.controller_Tests_Right_hand_Tip;
            }
        }
    }
}
